"use client";

import { useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { Badge, Card, Empty, ErrorState, Loading, PageIntro } from "@/components/ui";
import { api } from "@/lib/api";
import type { Entity } from "@/types";

export default function DatabasePage() { const { id } = useParams<{ id: string }>(); const [data, setData] = useState<Entity[] | null>(null); const [error, setError] = useState(""); useEffect(() => { api.database(id).then(setData).catch(value => setError(value instanceof Error ? value.message : "Database unavailable")); }, [id]); const relations = useMemo(() => data?.flatMap(entity => entity.fields.filter(field => field.foreign_key).map(field => ({ source: entity.name, field: field.name, target: field.foreign_key ?? "unknown" }))) ?? [], [data]); if (error) return <div className="py-10"><ErrorState message={error} /></div>; if (!data) return <div className="py-10"><Loading /></div>; return <div className="py-10"><PageIntro eyebrow="Blueprint / data model" title="Database design" description="Entity cards, keys, ownership, and relationship paths derived from the generated blueprint." /><Card title="Relationship map" action={<Badge>{relations.length} foreign keys</Badge>}><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{relations.length ? relations.map(relation => <div key={`${relation.source}-${relation.field}`} className="rounded-xl border border-[var(--line)] bg-[var(--peach)] p-4"><div className="flex flex-wrap items-center gap-2"><span className="badge">{relation.source}</span><span className="text-lg font-bold text-[var(--accent)]">→</span><span className="badge">{relation.target.split(".")[0]}</span></div><p className="muted mt-3 font-mono text-xs">{relation.source}.{relation.field} → {relation.target}</p></div>) : <p className="muted text-sm">No explicit foreign-key relationships were generated.</p>}</div></Card><div className="mt-5 grid gap-5 lg:grid-cols-2">{data.length === 0 ? <Empty /> : data.map(entity => <Card key={entity.id} title={entity.name} action={<Badge>{entity.fields.length} fields</Badge>}><p className="muted mb-5 text-sm">{entity.description}</p><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-[var(--line)] text-xs uppercase text-[var(--muted)]"><th className="pb-2">Field</th><th className="pb-2">Type</th><th className="pb-2">Rules</th></tr></thead><tbody>{entity.fields.map(field => <tr className="border-b border-[var(--line)] last:border-0" key={field.id}><td className="py-3 font-semibold">{field.name}</td><td className="py-3 text-[var(--muted)]">{field.data_type}</td><td className="py-3">{field.primary_key && <Badge>PK</Badge>} {field.unique && <Badge>unique</Badge>} {!field.nullable && <span className="muted text-xs">required</span>}{field.foreign_key && <p className="mt-1 text-xs text-[var(--accent)]">FK → {field.foreign_key}</p>}</td></tr>)}</tbody></table></div></Card>)}</div></div>; }
