"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { Badge, Card, Empty, ErrorState, Loading, PageIntro } from "@/components/ui";
import { api } from "@/lib/api";
import type { Project, Requirement, TraceabilityLink } from "@/types";

export default function Requirements() {
  const { id } = useParams<{ id: string }>(); const [items, setItems] = useState<Requirement[] | null>(null); const [project, setProject] = useState<Project | null>(null); const [trace, setTrace] = useState<TraceabilityLink[]>([]); const [error, setError] = useState("");
  useEffect(() => { Promise.all([api.requirements(id), api.project(id), api.traceability(id)]).then(([requirements, detail, traceability]) => { setItems(requirements); setProject(detail); setTrace(traceability); }).catch(value => setError(value instanceof Error ? value.message : "Requirements unavailable")); }, [id]);
  if (error) return <div className="py-10"><ErrorState message={error} /></div>; if (!items || !project) return <div className="py-10"><Loading /></div>;
  const lists: [string, string[]][] = [["Assumptions", project.assumptions], ["Constraints", project.constraints], ["Risks", project.risks], ["Open questions", project.open_questions]];
  return <div className="py-10"><PageIntro eyebrow="Blueprint / intelligence" title="Requirements" description="Requirements are connected to features, modules, APIs, delivery tasks, and their owners." /><div className="grid gap-4 lg:grid-cols-2"><Card title="Actors"><div className="flex flex-wrap gap-2">{project.actors.length ? project.actors.map(actor => <Badge key={actor}>{actor}</Badge>) : <span className="muted text-sm">No actors generated yet.</span>}</div></Card><Card title="Objective"><p className="muted leading-7">{project.objective || "No objective generated yet."}</p></Card></div><div className="mt-5 grid gap-4 sm:grid-cols-2">{lists.map(([title, values]) => <Card key={title} title={title}><ul className="muted list-disc space-y-2 pl-5 text-sm">{values.length ? values.map(item => <li key={item}>{item}</li>) : <li>None recorded</li>}</ul></Card>)}</div><Card title="Traceability map" action={<Badge>{trace.filter(item => item.coverage === "covered").length} covered</Badge>}><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b border-[var(--line)] text-xs uppercase tracking-wide text-[var(--muted)]"><th className="pb-3 pr-4">Requirement</th><th className="pb-3 pr-4">Feature / module</th><th className="pb-3 pr-4">API</th><th className="pb-3 pr-4">Task</th><th className="pb-3">Owner</th></tr></thead><tbody>{trace.map(item => <tr key={item.requirement_id} className="border-b border-[var(--line)] last:border-0"><td className="py-4 pr-4 font-semibold">{item.requirement_title}</td><td className="py-4 pr-4">{item.feature_name ?? "—"}<span className="muted block text-xs">{item.module_name ?? "Unmapped"}</span></td><td className="py-4 pr-4 font-mono text-xs">{item.api_path ?? "—"}</td><td className="py-4 pr-4">{item.task_key ?? "—"}</td><td className="py-4">{item.owner_name ?? "Unassigned"}<span className={`block text-xs ${item.coverage === "covered" ? "text-[var(--green)]" : "text-[#a66a16]"}`}>{item.coverage}</span></td></tr>)}</tbody></table></div></Card><div className="mt-5 grid gap-4">{items.length === 0 ? <Empty /> : items.map(item => <Card key={item.id} title={item.title} action={<Badge>{item.priority}</Badge>}><div className="flex gap-2"><Badge>{item.category.replace("_", " ")}</Badge><span className="muted text-xs">source: {item.source}</span></div><p className="muted mt-4 leading-7">{item.description}</p></Card>)}</div></div>;
}
