"use client";

import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { api } from "@/lib/api";
import type { Activity, Project } from "@/types";

export function Shell({ children }: { children: React.ReactNode }) {
  return <main className="min-h-screen"><header className="topbar"><div className="mx-auto flex max-w-[1440px] items-center justify-between gap-5 px-5 py-4 lg:px-8"><Link href="/" className="focus-ring flex items-center gap-3 text-lg font-bold"><span className="brand-mark">M</span><span>MindStream <span className="muted font-normal">AI</span></span></Link><div className="flex items-center gap-3"><Link href="/search" className="focus-ring hidden rounded-xl border border-[var(--line)] bg-[var(--panel)] px-3 py-2 text-sm font-semibold sm:block">⌕ Search</Link><Link href="/reports" className="focus-ring hidden rounded-xl border border-[var(--line)] bg-[var(--panel)] px-3 py-2 text-sm font-semibold lg:block">Reports</Link><ProjectSwitcher /><ThemeToggle /><span className="avatar hidden sm:inline-flex">AM</span></div></div></header>{children}</main>;
}

export function ProjectSwitcher() {
  const pathname = usePathname(); const router = useRouter(); const [projects, setProjects] = useState<Project[]>([]); const [open, setOpen] = useState(false); const [query, setQuery] = useState("");
  useEffect(() => { api.projects().then(setProjects).catch(() => undefined); }, []);
  const currentId = pathname.match(/\/project\/([^/]+)/)?.[1]; const current = projects.find(item => item.id === currentId);
  const visible = projects.filter(item => item.name.toLowerCase().includes(query.toLowerCase()));
  return <div className="relative"><button onClick={() => setOpen(value => !value)} className="focus-ring switcher-button" aria-expanded={open}><span className="hidden text-left sm:block"><span className="eyebrow block">Current project</span><span className="block max-w-44 truncate text-sm font-semibold">{current?.name ?? "All projects"}</span></span><span aria-hidden="true">⌄</span></button>{open && <><button className="fixed inset-0 z-20 cursor-default" aria-label="Close project switcher" onClick={() => setOpen(false)} /><div className="card absolute right-0 z-30 mt-3 w-80 p-3"><p className="eyebrow px-2 py-2">Switch project</p><input autoFocus value={query} onChange={event => setQuery(event.target.value)} placeholder="Search projects..." className="focus-ring mb-2 w-full rounded-xl border border-[var(--line)] bg-[var(--paper)] px-3 py-2 text-sm" />{visible.map(item => <button key={item.id} onClick={() => { setOpen(false); router.push(`/project/${item.id}`); }} className="focus-ring flex w-full items-center justify-between rounded-xl px-3 py-3 text-left hover:bg-[var(--peach)]"><span><span className="block text-sm font-semibold">{item.name}</span><span className="muted text-xs">{item.domain}</span></span><StatusBadge status={item.status} /></button>)}{visible.length === 0 && <p className="muted px-3 py-4 text-sm">No projects found.</p>}<Link href="/" onClick={() => setOpen(false)} className="focus-ring mt-1 block rounded-xl px-3 py-2 text-sm font-semibold text-[var(--accent)] hover:bg-[var(--peach)]">View all projects →</Link></div></>}</div>;
}

function ThemeToggle() { const [dark, setDark] = useState(false); useEffect(() => { setDark(document.documentElement.dataset.theme === "dark"); }, []); return <button className="focus-ring icon-button" aria-label="Toggle theme" onClick={() => { const next = !dark; document.documentElement.dataset.theme = next ? "dark" : "light"; setDark(next); }}>☼</button>; }
export function Loading() { return <div className="card flex items-center gap-3 p-8 text-center muted"><span className="spinner" />Loading intelligence...</div>; }
export function ErrorState({ message }: { message: string }) { return <div className="card border-red-200 bg-red-50 p-6 text-red-800"><p className="font-semibold">We couldn&apos;t load this view</p><p className="mt-1 text-sm">{message}</p></div>; }
export function Empty({ text = "No data yet. Run analysis to generate this section." }: { text?: string }) { return <div className="card border-dashed p-10 text-center muted">{text}</div>; }
export function Card({ title, children, action }: { title: string; children: React.ReactNode; action?: React.ReactNode }) { return <section className="card p-5 sm:p-6"><div className="mb-5 flex items-center justify-between gap-4"><h2 className="text-lg font-bold">{title}</h2>{action}</div>{children}</section>; }
export function Badge({ children }: { children: React.ReactNode }) { return <span className="badge">{children}</span>; }
export function StatusBadge({ status }: { status: string }) { return <span className={`status status-${status}`}><span className="status-dot" />{status.replaceAll("_", " ")}</span>; }
export function MetricCard({ label, value, hint, accent = "purple" }: { label: string; value: string | number; hint?: string; accent?: string }) { return <div className={`metric-card metric-${accent}`}><p className="muted text-xs font-semibold uppercase tracking-[.12em]">{label}</p><p className="mt-3 text-3xl font-bold tracking-tight">{value}</p>{hint && <p className="muted mt-1 text-xs">{hint}</p>}</div>; }
export function ProgressBar({ value }: { value: number }) { return <div className="progress-track" aria-label={`${value}% complete`}><span style={{ width: `${Math.max(0, Math.min(100, value))}%` }} /></div>; }
export function PageIntro({ eyebrow, title, description, action }: { eyebrow: string; title: string; description?: string; action?: React.ReactNode }) { return <div className="mb-8 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow">{eyebrow}</p><h1 className="mt-2 text-4xl font-bold tracking-tight sm:text-5xl">{title}</h1>{description && <p className="muted mt-3 max-w-2xl leading-7">{description}</p>}</div>{action}</div>; }
export function ProjectCard({ project }: { project: Project }) { return <Link href={`/project/${project.id}`} className="card project-card focus-ring block"><div className="flex items-start justify-between gap-4"><div className="project-icon">{project.name.slice(0, 1)}</div><StatusBadge status={project.status} /></div><p className="eyebrow mt-6">{project.domain}</p><h2 className="mt-2 text-xl font-bold">{project.name}</h2><p className="muted mt-2 line-clamp-2 text-sm leading-6">{project.description}</p><div className="mt-6 flex items-end justify-between"><div><p className="muted text-xs">Project health</p><p className="mt-1 text-2xl font-bold">{project.health_score}<span className="muted text-sm"> / 100</span></p></div><span className="text-sm font-semibold text-[var(--accent)]">Open →</span></div><ProgressBar value={project.progress} /><div className="muted mt-4 flex gap-3 text-xs"><span>{project.team_member_count} people</span><span>·</span><span>{project.task_count} tasks</span><span>·</span><span>{project.report_count} reports</span></div></Link>; }
export function ActivityTimeline({ items }: { items: Activity[] }) { return <div className="space-y-1">{items.length === 0 ? <Empty text="No activity recorded yet." /> : items.map(item => <div key={item.id} className="timeline-item"><span className="timeline-dot" /><div><p className="text-sm font-semibold">{item.action}</p><p className="muted mt-1 text-xs">{item.actor_name} · {new Date(item.created_at).toLocaleDateString()}</p><p className="muted mt-1 text-sm">{item.details}</p></div></div>)}</div>; }
