"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { Card, Empty, ErrorState, Loading, PageIntro, StatusBadge } from "@/components/ui";
import { api } from "@/lib/api";
import type { Project, ProjectComparison } from "@/types";

export default function ComparePage() {
  const [projects, setProjects] = useState<Project[] | null>(null); const [selected, setSelected] = useState<string[]>([]); const [comparison, setComparison] = useState<ProjectComparison[] | null>(null); const [error, setError] = useState("");
  useEffect(() => { api.projects().then(setProjects).catch(value => setError(value instanceof Error ? value.message : "Projects unavailable")); }, []);
  const toggle = (id: string) => setSelected(current => current.includes(id) ? current.filter(value => value !== id) : current.length < 4 ? [...current, id] : current);
  async function compare() { setError(""); try { setComparison(await api.compare(selected)); } catch (value) { setError(value instanceof Error ? value.message : "Could not compare projects"); } }
  const rows = useMemo(() => [{ label: "Health", key: "health_score" }, { label: "Progress", key: "progress" }, { label: "Requirements", key: "requirements" }, { label: "Features", key: "features" }, { label: "Modules", key: "modules" }, { label: "APIs", key: "apis" }, { label: "Tasks", key: "tasks" }, { label: "Team", key: "team" }, { label: "Risks", key: "risks" }] as const, []);
  if (error && !projects) return <div className="mx-auto max-w-7xl px-5 py-12 lg:px-8"><ErrorState message={error} /></div>; if (!projects) return <div className="mx-auto max-w-7xl px-5 py-12 lg:px-8"><Loading /></div>;
  return <div className="mx-auto max-w-[1200px] px-5 py-10 lg:px-8"><PageIntro eyebrow="Workspace / decisions" title="Compare projects" description="Select two to four projects to compare health, delivery shape, ownership, and risk at a glance." action={<button disabled={selected.length < 2} onClick={compare} className="focus-ring rounded-xl bg-[var(--ink)] px-4 py-3 text-sm font-bold text-[var(--panel)] disabled:opacity-40">Compare {selected.length || ""}</button>} /><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{projects.map(project => <button key={project.id} onClick={() => toggle(project.id)} className={`focus-ring rounded-2xl border p-4 text-left ${selected.includes(project.id) ? "border-[var(--accent)] bg-[var(--peach)]" : "border-[var(--line)] bg-[var(--panel)]"}`}><div className="flex items-start justify-between gap-3"><span className="project-icon">{project.name.slice(0, 1)}</span><StatusBadge status={project.status} /></div><p className="mt-4 font-bold">{project.name}</p><p className="muted mt-1 text-xs">{project.domain}</p></button>)}</div>{error && <p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{comparison && comparison.length > 0 && <div className="mt-6"><Card title="Comparison matrix"><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead><tr className="border-b border-[var(--line)]"><th className="pb-3">Signal</th>{comparison.map(item => <th className="pb-3" key={item.id}><Link href={`/project/${item.id}`} className="hover:text-[var(--accent)]">{item.name}</Link></th>)}</tr></thead><tbody>{rows.map(row => <tr key={row.key} className="border-b border-[var(--line)] last:border-0"><td className="py-4 font-semibold">{row.label}</td>{comparison.map(item => <td className="py-4" key={item.id}>{item[row.key]}{row.key === "health_score" ? " / 100" : row.key === "progress" ? "%" : ""}</td>)}</tr>)}</tbody></table></div></Card></div>}{comparison && comparison.length === 0 && <div className="mt-6"><Empty text="Select at least two projects to compare." /></div>}</div>;
}
