"use client";
import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { api } from "@/lib/api";
import { Card, ErrorState, Loading, Badge } from "@/components/ui";
import type { Project } from "@/types";

export default function Dashboard() {
  const params = useParams<{ id: string }>(); const router = useRouter();
  const [project, setProject] = useState<Project | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { api.project(params.id).then(setProject).catch((e) => setError(e.message)); }, [params.id]);
  if (error) return <div className="py-10"><ErrorState message={error} /></div>; if (!project) return <div className="py-10"><Loading /></div>;
  const currentProject = project;
  async function analyze() { setBusy(true); setError(""); try { await api.analyze(currentProject.id); setProject(await api.project(currentProject.id)); } catch (e) { setError(e instanceof Error ? e.message : "Generation failed"); } finally { setBusy(false); } }
  const metrics = [["Requirements", project.requirement_count, "requirements"], ["Components", project.component_count, "architecture components"], ["Entities", project.entity_count, "database entities"], ["Tasks", project.task_count, "implementation tasks"], ["Roles", project.role_count, "team roles"], ["Documents", project.document_count, "generated documents"]];
  return <div className="py-10"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow">Project dashboard</p><h1 className="mt-2 text-4xl font-bold">{project.name}</h1><p className="muted mt-3 max-w-3xl leading-7">{project.description}</p><p className="muted mt-3 text-sm">{project.generation_status ? `Generation: ${project.generation_status}` : "Not analyzed yet"}</p></div><div className="flex items-center gap-3"><Badge>{project.status}</Badge><button onClick={analyze} disabled={busy} className="focus-ring rounded-xl bg-indigo-600 px-4 py-3 text-sm font-semibold text-white disabled:opacity-60">{busy ? "Generating..." : project.status === "completed" ? "Regenerate plan" : "Analyze project"}</button></div></div>{error && <p className="mt-5 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{project.status !== "completed" && <div className="card mt-8 border-indigo-100 bg-indigo-50 p-6"><p className="font-semibold">Your blueprint is waiting for analysis.</p><p className="muted mt-1 text-sm">The deterministic mock provider completes all stages locally.</p></div>}<div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-6">{metrics.map(([label, value, hint]) => <div className="card p-5" key={label as string}><p className="muted text-sm">{label}</p><p className="mt-3 text-3xl font-bold">{value}</p><p className="muted mt-1 text-xs">{hint}</p></div>)}</div><div className="mt-8 grid gap-6 lg:grid-cols-2"><Card title="Generated objective"><p className="muted leading-7">{project.objective || "Run analysis to generate a project objective."}</p><p className="muted mt-5 text-sm"><span className="font-semibold text-slate-700">Actors:</span> {project.actors.join(", ") || "Not generated yet"}</p></Card><Card title="Project context"><dl className="space-y-4 text-sm"><div><dt className="muted">Target users</dt><dd className="mt-1 font-semibold">{project.target_users.join(", ") || "Not specified"}</dd></div><div><dt className="muted">Preferred stack</dt><dd className="mt-1 font-semibold">{project.preferred_stack.join(", ") || "Planner defaults"}</dd></div></dl></Card></div><div className="mt-6"><Card title="Quick links"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{["requirements", "architecture", "database", "tasks"].map(section => <button key={section} onClick={() => router.push(`/project/${project.id}/${section}`)} className="focus-ring rounded-xl border border-slate-200 p-4 text-left font-semibold capitalize hover:border-indigo-300 hover:bg-indigo-50">View {section} →</button>)}</div></Card></div></div>;
}
