"use client";

import { useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { Badge, Card, Empty, ErrorState, Loading, PageIntro, StatusBadge } from "@/components/ui";
import { api } from "@/lib/api";
import type { Task } from "@/types";

const statuses = ["all", "todo", "in_progress", "blocked", "done"];

export default function TasksPage() {
  const { id } = useParams<{ id: string }>(); const [data, setData] = useState<Task[] | null>(null); const [error, setError] = useState(""); const [status, setStatus] = useState("all"); const [priority, setPriority] = useState("all"); const [owner, setOwner] = useState("all");
  useEffect(() => { api.tasks(id).then(setData).catch(value => setError(value instanceof Error ? value.message : "Tasks unavailable")); }, [id]);
  const owners = useMemo(() => Array.from(new Set(data?.map(item => item.owner_name).filter(Boolean) as string[])).sort(), [data]);
  const visible = useMemo(() => data?.filter(item => (status === "all" || item.status === status) && (priority === "all" || item.priority === priority) && (owner === "all" || item.owner_name === owner)) ?? [], [data, status, priority, owner]);
  const done = data?.filter(item => item.status === "done").length ?? 0;
  if (error) return <div className="py-10"><ErrorState message={error} /></div>; if (!data) return <div className="py-10"><Loading /></div>;
  return <div className="py-10"><PageIntro eyebrow="Blueprint / delivery" title="Tasks" description="Dependency-aware work with status, ownership, module context, and acceptance criteria." /><div className="mb-5 grid gap-3 sm:grid-cols-3"><div className="metric-card metric-purple"><p className="muted text-xs">Total work</p><p className="mt-2 text-3xl font-bold">{data.length}</p></div><div className="metric-card metric-green"><p className="muted text-xs">Completed</p><p className="mt-2 text-3xl font-bold">{done}</p></div><div className="metric-card metric-yellow"><p className="muted text-xs">Completion</p><p className="mt-2 text-3xl font-bold">{data.length ? Math.round(done / data.length * 100) : 0}%</p></div></div><div className="mb-6 flex flex-wrap items-center gap-2"><span className="muted text-sm">Status:</span>{statuses.map(value => <button key={value} onClick={() => setStatus(value)} className={`focus-ring rounded-lg px-3 py-2 text-xs font-bold ${status === value ? "bg-[var(--ink)] text-[var(--panel)]" : "border border-[var(--line)] bg-[var(--panel)]"}`}>{value.replaceAll("_", " ")}</button>)}<select value={priority} onChange={event => setPriority(event.target.value)} className="focus-ring rounded-lg border border-[var(--line)] bg-[var(--panel)] px-3 py-2 text-xs font-bold"><option value="all">All priorities</option>{["critical", "high", "medium", "low"].map(value => <option key={value}>{value}</option>)}</select><select value={owner} onChange={event => setOwner(event.target.value)} className="focus-ring rounded-lg border border-[var(--line)] bg-[var(--panel)] px-3 py-2 text-xs font-bold"><option value="all">All owners</option>{owners.map(value => <option key={value}>{value}</option>)}</select></div><div className="grid gap-4">{visible.length === 0 ? <Empty text="No tasks match these filters." /> : visible.map(item => <Card key={item.id} title={`${item.task_key} · ${item.title}`} action={<div className="flex gap-2"><Badge>{item.priority}</Badge><StatusBadge status={item.status} /></div>}><div className="flex flex-wrap gap-2"><Badge>{item.owner_name || "Unassigned"}</Badge><Badge>{item.module_name || "Core module"}</Badge>{item.feature_name && <Badge>{item.feature_name}</Badge>}</div><p className="muted mt-3 leading-6">{item.description}</p><div className="mt-4 grid gap-3 text-sm sm:grid-cols-3"><div><p className="muted text-xs">Role</p><p className="mt-1 font-semibold">{item.role_name || "Unassigned"}</p></div><div><p className="muted text-xs">Effort</p><p className="mt-1 font-semibold">{item.effort} points</p></div><div><p className="muted text-xs">Dependencies</p><p className="mt-1 font-semibold">{item.dependency_ids.length || "None"}</p></div></div><h3 className="mt-4 text-sm font-bold">Acceptance criteria</h3><ul className="muted mt-2 list-disc space-y-1 pl-5 text-sm">{item.acceptance_criteria.map(criteria => <li key={criteria}>{criteria}</li>)}</ul></Card>)}</div></div>;
}
