"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { Badge, Card, Empty, ErrorState, Loading, PageIntro, ProgressBar } from "@/components/ui";
import { api } from "@/lib/api";
import type { ProjectMember, Role } from "@/types";

export default function TeamPage() { const { id } = useParams<{ id: string }>(); const [members, setMembers] = useState<ProjectMember[] | null>(null); const [roles, setRoles] = useState<Role[]>([]); const [error, setError] = useState(""); useEffect(() => { Promise.all([api.peopleForProject(id), api.team(id)]).then(([people, roleData]) => { setMembers(people); setRoles(roleData); }).catch(value => setError(value instanceof Error ? value.message : "Team unavailable")); }, [id]); if (error) return <div className="py-10"><ErrorState message={error} /></div>; if (!members) return <div className="py-10"><Loading /></div>; return <div className="py-10"><PageIntro eyebrow="Project / people" title="Team" description="Actual project members, their responsibilities, workload, and delivery contribution." /><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{members.length === 0 ? <Empty /> : members.map(member => <Card key={member.id} title={member.name} action={<span className="avatar inline-flex">{member.name.split(" ").map(part => part[0]).join("")}</span>}><p className="eyebrow">{member.role_title}</p><p className="muted mt-2 text-sm">{member.title}</p><div className="mt-5 flex justify-between text-sm"><span>{member.assigned_task_count} assigned tasks</span><span>{member.completed_task_count} done</span></div><div className="mt-2"><ProgressBar value={member.assigned_task_count ? member.completed_task_count / member.assigned_task_count * 100 : 0} /></div><p className="muted mt-4 text-xs">Workload {member.workload_percent}%</p><div className="mt-3 flex flex-wrap gap-2">{member.modules.map(module => <Badge key={module}>{module}</Badge>)}</div><Link href={`/people/${member.person_id}`} className="focus-ring mt-5 inline-block text-sm font-bold text-[var(--accent)]">Open profile →</Link></Card>)}</div><Card title="Blueprint roles" action={<Badge>{roles.length} roles</Badge>}><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{roles.map(role => <div key={role.id} className="rounded-xl border border-[var(--line)] p-4"><p className="font-semibold">{role.name}</p><p className="muted mt-2 text-sm leading-6">{role.description}</p></div>)}</div></Card></div>; }
