"""initial schema

Revision ID: 5931e7e69974
Revises: 
Create Date: 2026-09-09 08:15:46.506175
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '5931e7e69974'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_users', sa.JSON(), nullable=False),
    sa.Column('preferred_stack', sa.JSON(), nullable=False),
    sa.Column('team_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('architecture_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('style', sa.String(length=100), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('components_json', sa.JSON(), nullable=False),
    sa.Column('technologies_json', sa.JSON(), nullable=False),
    sa.Column('communication_paths', sa.JSON(), nullable=False),
    sa.Column('deployment_concept', sa.Text(), nullable=False),
    sa.Column('scalability_considerations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('database_entities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name')
    )
    op.create_index('ix_database_entities_project_id', 'database_entities', ['project_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('document_type', sa.String(length=40), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_project_id', 'documents', ['project_id'], unique=False)
    op.create_table('generation_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('run_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_stage', sa.String(length=40), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_generation_runs_project_id', 'generation_runs', ['project_id'], unique=False)
    op.create_table('requirements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_requirements_project_id', 'requirements', ['project_id'], unique=False)
    op.create_table('team_roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name')
    )
    op.create_index('ix_team_roles_project_id', 'team_roles', ['project_id'], unique=False)
    op.create_table('database_fields',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('nullable', sa.Boolean(), nullable=False),
    sa.Column('primary_key', sa.Boolean(), nullable=False),
    sa.Column('unique', sa.Boolean(), nullable=False),
    sa.Column('default_value', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['database_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'name')
    )
    op.create_index('ix_database_fields_entity_id', 'database_fields', ['entity_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('task_type', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('effort', sa.Integer(), nullable=False),
    sa.Column('acceptance_criteria', sa.JSON(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['team_roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_project_id', 'tasks', ['project_id'], unique=False)
    op.create_index('ix_tasks_role_id', 'tasks', ['role_id'], unique=False)
    op.create_table('dependencies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('depends_on_task_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'depends_on_task_id')
    )
    op.create_index('ix_dependencies_task_id', 'dependencies', ['task_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dependencies_task_id', table_name='dependencies')
    op.drop_table('dependencies')
    op.drop_index('ix_tasks_role_id', table_name='tasks')
    op.drop_index('ix_tasks_project_id', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_database_fields_entity_id', table_name='database_fields')
    op.drop_table('database_fields')
    op.drop_index('ix_team_roles_project_id', table_name='team_roles')
    op.drop_table('team_roles')
    op.drop_index('ix_requirements_project_id', table_name='requirements')
    op.drop_table('requirements')
    op.drop_index('ix_generation_runs_project_id', table_name='generation_runs')
    op.drop_table('generation_runs')
    op.drop_index('ix_documents_project_id', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_database_entities_project_id', table_name='database_entities')
    op.drop_table('database_entities')
    op.drop_table('architecture_plans')
    op.drop_table('projects')
    # ### end Alembic commands ###
