"""persist blueprint context

Revision ID: f9b58b1780af
Revises: 5931e7e69974
Create Date: 2026-09-09 09:14:43.945001
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = 'f9b58b1780af'
down_revision: Union[str, Sequence[str], None] = '5931e7e69974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('database_fields', sa.Column('foreign_key', sa.String(length=120), nullable=True))
    op.add_column('projects', sa.Column('objective', sa.Text(), server_default='', nullable=False))
    op.add_column('projects', sa.Column('actors', sa.JSON(), server_default='[]', nullable=False))
    op.add_column('projects', sa.Column('assumptions', sa.JSON(), server_default='[]', nullable=False))
    op.add_column('projects', sa.Column('constraints', sa.JSON(), server_default='[]', nullable=False))
    op.add_column('projects', sa.Column('risks', sa.JSON(), server_default='[]', nullable=False))
    op.add_column('projects', sa.Column('open_questions', sa.JSON(), server_default='[]', nullable=False))
    op.add_column('tasks', sa.Column('task_key', sa.String(length=20), server_default='legacy', nullable=False))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'task_key')
    op.drop_column('projects', 'open_questions')
    op.drop_column('projects', 'risks')
    op.drop_column('projects', 'constraints')
    op.drop_column('projects', 'assumptions')
    op.drop_column('projects', 'actors')
    op.drop_column('projects', 'objective')
    op.drop_column('database_fields', 'foreign_key')
    # ### end Alembic commands ###
