"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { Shell } from "@/components/ui";
import { api } from "@/lib/api";

export default function NewProject() { const router = useRouter(); const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [users, setUsers] = useState("students, junior developers"); const [stack, setStack] = useState("Next.js, FastAPI, PostgreSQL"); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); if (description.trim().length < 20) { setError("Add at least 20 characters describing the project."); return; } setBusy(true); try { const project = await api.create({ name, description, target_users: users.split(",").map(x => x.trim()).filter(Boolean), preferred_stack: stack.split(",").map(x => x.trim()).filter(Boolean) }); router.push(`/project/${project.id}`); } catch (err) { setError(err instanceof Error ? err.message : "Could not create project"); setBusy(false); } }
  return <Shell><div className="mx-auto max-w-3xl px-6 py-12"><Link href="/" className="muted text-sm">← Back home</Link><p className="eyebrow mt-10">New blueprint</p><h1 className="mt-3 text-4xl font-bold">Tell us what you want to build.</h1><p className="muted mt-3">The mock planner will turn this context into an actionable, reviewable plan.</p><form onSubmit={submit} className="card mt-8 space-y-6 p-7"><label className="block"><span className="mb-2 block font-semibold">Project name</span><input required minLength={2} maxLength={120} value={name} onChange={e => setName(e.target.value)} placeholder="e.g. Campus Course Hub" className="focus-ring w-full rounded-xl border border-slate-300 px-4 py-3" /></label><label className="block"><span className="mb-2 block font-semibold">Project description</span><textarea required minLength={20} maxLength={10000} value={description} onChange={e => setDescription(e.target.value)} placeholder="Describe the users, problem, key workflows, and constraints…" rows={8} className="focus-ring w-full rounded-xl border border-slate-300 px-4 py-3" /></label><label className="block"><span className="mb-2 block font-semibold">Target users <span className="muted font-normal">(comma-separated)</span></span><input value={users} onChange={e => setUsers(e.target.value)} className="focus-ring w-full rounded-xl border border-slate-300 px-4 py-3" /></label><label className="block"><span className="mb-2 block font-semibold">Preferred technologies <span className="muted font-normal">(optional)</span></span><input value={stack} onChange={e => setStack(e.target.value)} className="focus-ring w-full rounded-xl border border-slate-300 px-4 py-3" /></label>{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={busy} className="focus-ring w-full rounded-xl bg-indigo-600 px-5 py-3 font-semibold text-white disabled:cursor-wait disabled:opacity-60">{busy ? "Creating…" : "Create project"}</button></form></div></Shell>; }
