"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Shell } from "@/components/ui";
import { api } from "@/lib/api";

export default function NewProject() {
  const router = useRouter(); const [form, setForm] = useState({ name: "", description: "", domain: "Software", users: "students, project teams", stack: "Next.js, FastAPI, PostgreSQL", objective: "", timeline: "12 weeks", owner: "Alex Morgan", risks: "" }); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  function update(field: keyof typeof form, value: string) { setForm(current => ({ ...current, [field]: value })); }
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); if (form.description.trim().length < 20) { setError("Add at least 20 characters describing the project."); return; } setBusy(true); try { const project = await api.create({ name: form.name, description: form.description, domain: form.domain, objective: form.objective, expected_timeline: form.timeline, owner_name: form.owner, target_users: form.users.split(",").map(item => item.trim()).filter(Boolean), preferred_stack: form.stack.split(",").map(item => item.trim()).filter(Boolean), important_risks: form.risks.split(",").map(item => item.trim()).filter(Boolean) }); router.push(`/project/${project.id}`); } catch (value) { setError(value instanceof Error ? value.message : "Could not create project"); setBusy(false); } }
  return <Shell><div className="mx-auto max-w-4xl px-5 py-10 lg:px-8"><Link href="/" className="muted text-sm">← Back to workspace</Link><div className="mt-10"><p className="eyebrow">New project intelligence</p><h1 className="mt-3 text-4xl font-bold tracking-tight">Start with the context.</h1><p className="muted mt-3 max-w-2xl leading-7">Give the planner enough signal to create a useful blueprint. Optional fields can be refined after the first analysis.</p></div><form onSubmit={submit} className="card mt-8 space-y-6 p-5 sm:p-8"><div className="grid gap-6 md:grid-cols-2"><Field label="Project name" value={form.name} onChange={value => update("name", value)} placeholder="e.g. Campus Course Hub" required /><Field label="Domain" value={form.domain} onChange={value => update("domain", value)} placeholder="Education, healthcare, logistics..." /><Field label="Project owner" value={form.owner} onChange={value => update("owner", value)} /><Field label="Expected timeline" value={form.timeline} onChange={value => update("timeline", value)} /></div><label className="block"><span className="mb-2 block font-semibold">Project description <span className="muted font-normal">(required)</span></span><textarea required minLength={20} maxLength={10000} value={form.description} onChange={event => update("description", event.target.value)} placeholder="Describe the users, problem, key workflows, and constraints..." rows={7} className="focus-ring w-full rounded-xl border border-[var(--line)] bg-[var(--paper)] px-4 py-3" /></label><label className="block"><span className="mb-2 block font-semibold">Primary objective <span className="muted font-normal">(optional)</span></span><textarea value={form.objective} onChange={event => update("objective", event.target.value)} placeholder="What outcome should this project make possible?" rows={3} className="focus-ring w-full rounded-xl border border-[var(--line)] bg-[var(--paper)] px-4 py-3" /></label><div className="grid gap-6 md:grid-cols-2"><Field label="Target users" hint="comma-separated" value={form.users} onChange={value => update("users", value)} /><Field label="Preferred technologies" hint="comma-separated" value={form.stack} onChange={value => update("stack", value)} /><Field label="Important risks" hint="comma-separated, optional" value={form.risks} onChange={value => update("risks", value)} /></div>{error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={busy} className="focus-ring w-full rounded-xl bg-[var(--ink)] px-5 py-3 font-bold text-[var(--panel)] disabled:cursor-wait disabled:opacity-60">{busy ? "Creating workspace..." : "Create and open project"}</button></form></div></Shell>;
}

function Field({ label, hint, value, onChange, placeholder, required = false }: { label: string; hint?: string; value: string; onChange: (value: string) => void; placeholder?: string; required?: boolean }) { return <label className="block"><span className="mb-2 block font-semibold">{label} {hint && <span className="muted font-normal">({hint})</span>}</span><input required={required} minLength={required ? 2 : undefined} value={value} onChange={event => onChange(event.target.value)} placeholder={placeholder} className="focus-ring w-full rounded-xl border border-[var(--line)] bg-[var(--paper)] px-4 py-3" /></label>; }
